// PROJECTS
export const CHANGE_BOOTCAMP_PROJECT = 'CHANGE_BOOTCAMP_PROJECT'
export const CHANGE_CENTER_PROJECT = 'CHANGE_CENTER_PROJECT'
export const CHANGE_STATE_PROJECT = 'CHANGE_STATE_PROJECT'
export const CHANGE_ORDER_PROJECT = 'CHANGE_ORDER_PROJECT'

//JOBS
export const CHANGE_BOOTCAMP_JOB = 'CHANGE_BOOTCAMP_JOB'
export const CHANGE_LOCATION_JOB = 'CHANGE_LOCATION_JOB'
export const CHANGE_COMPANY_JOB = 'CHANGE_COMPANY_JOB'
