import { Component, OnInit } from '@angular/core';
import { select } from '@angular-redux/store';

@Component({
  selector: 'app-projects-container',
  templateUrl: './projects-container.component.html',
  styleUrls: ['./projects-container.component.css']
})
export class ProjectsContainerComponent implements OnInit {
  
  @select(['projects', 'bootcamp']) bootcamp: string;
  @select(['projects', 'center']) center: string;
  @select(['projects', 'state']) state: string;
  @select(['projects', 'order']) order: string;

  projectsArray : any []

  constructor() { 
    this.projectsArray = [
      { id: 1, author: 'Javier Vázquez', imageAuthor: '../../../assets/images/foto_linkedin_javi.png', title: 'Project A', objetive: 'Social Network for Neolanders', bootcamp: 'Full-Stack', description:'Lorem fistrum no puedor te va a hasé pupitaa te va a hasé pupitaa papaar papaar torpedo benemeritaar jarl condemor fistro. Te va a hasé pupitaa al ataquerl torpedo ese hombree al ataquerl la caidita tiene musho peligro qué dise usteer ese pedazo de te va a hasé pupitaa fistro. Fistro quietooor diodeno va usté muy cargadoo me cago en tus muelas va usté muy cargadoo.', image: '../../assets/images/projects/network.jpg'},
      {id: 2, author: 'Javier Vázquez', imageAuthor: '../../../assets/images/foto_linkedin_javi.png' ,title: 'Project B', objetive: 'A site for connecting artist and clubs', bootcamp: 'Full-Stack', description:'Lorem fistrum no puedor te va a hasé pupitaa te va a hasé pupitaa papaar papaar torpedo benemeritaar jarl condemor fistro. Te va a hasé pupitaa al ataquerl torpedo ese hombree al ataquerl la caidita tiene musho peligro qué dise usteer ese pedazo de te va a hasé pupitaa fistro. Fistro quietooor diodeno va usté muy cargadoo me cago en tus muelas va usté muy cargadoo.', image:'../../assets/images/projects/clubDisco.jpg'},
      {id: 3, author: 'Javier Vázquez', imageAuthor: '../../../assets/images/foto_linkedin_javi.png', title: 'Project C', objetive: 'App for helping dislexic people', bootcamp: 'UX/UI', description: 'Lorem fistrum no puedor te va a hasé pupitaa te va a hasé pupitaa papaar papaar torpedo benemeritaar jarl condemor fistro. Te va a hasé pupitaa al ataquerl torpedo ese hombree al ataquerl la caidita tiene musho peligro qué dise usteer ese pedazo de te va a hasé pupitaa fistro. Fistro quietooor diodeno va usté muy cargadoo me cago en tus muelas va usté muy cargadoo.', image: '../../assets/images/projects/dislexia.png' },
      {id: 1, author: 'Javier Vázquez', imageAuthor: '../../../assets/images/foto_linkedin_javi.png', title: 'Project A', objetive: 'Social Network for Neolanders', bootcamp: 'Full-Stack', description:'Lorem fistrum no puedor te va a hasé pupitaa te va a hasé pupitaa papaar papaar torpedo benemeritaar jarl condemor fistro. Te va a hasé pupitaa al ataquerl torpedo ese hombree al ataquerl la caidita tiene musho peligro qué dise usteer ese pedazo de te va a hasé pupitaa fistro. Fistro quietooor diodeno va usté muy cargadoo me cago en tus muelas va usté muy cargadoo.', image: '../../assets/images/projects/network.jpg'},
      {id: 2, author: 'Javier Vázquez', imageAuthor: '../../../assets/images/foto_linkedin_javi.png', title: 'Project B', objetive: 'A site for connecting artist and clubs', bootcamp: 'Full-Stack', description:'Lorem fistrum no puedor te va a hasé pupitaa te va a hasé pupitaa papaar papaar torpedo benemeritaar jarl condemor fistro. Te va a hasé pupitaa al ataquerl torpedo ese hombree al ataquerl la caidita tiene musho peligro qué dise usteer ese pedazo de te va a hasé pupitaa fistro. Fistro quietooor diodeno va usté muy cargadoo me cago en tus muelas va usté muy cargadoo.', image:'../../assets/images/projects/clubDisco.jpg'},
      {id: 3, author: 'Javier Vázquez', imageAuthor: '../../../assets/images/foto_linkedin_javi.png', title: 'Project C', objetive: 'App for helping dislexic people', bootcamp: 'UX/UI', description: 'Lorem fistrum no puedor te va a hasé pupitaa te va a hasé pupitaa papaar papaar torpedo benemeritaar jarl condemor fistro. Te va a hasé pupitaa al ataquerl torpedo ese hombree al ataquerl la caidita tiene musho peligro qué dise usteer ese pedazo de te va a hasé pupitaa fistro. Fistro quietooor diodeno va usté muy cargadoo me cago en tus muelas va usté muy cargadoo.', image: '../../assets/images/projects/dislexia.png' },
      {id: 1, author: 'Javier Vázquez', imageAuthor: '../../../assets/images/foto_linkedin_javi.png', title: 'Project A', objetive: 'Social Network for Neolanders', bootcamp: 'Full-Stack', description:'Lorem fistrum no puedor te va a hasé pupitaa te va a hasé pupitaa papaar papaar torpedo benemeritaar jarl condemor fistro. Te va a hasé pupitaa al ataquerl torpedo ese hombree al ataquerl la caidita tiene musho peligro qué dise usteer ese pedazo de te va a hasé pupitaa fistro. Fistro quietooor diodeno va usté muy cargadoo me cago en tus muelas va usté muy cargadoo.', image: '../../assets/images/projects/network.jpg'},
      {id: 2, author: 'Javier Vázquez', imageAuthor: '../../../assets/images/foto_linkedin_javi.png', title: 'Project B', objetive: 'A site for connecting artist and clubs', bootcamp: 'Full-Stack', description:'Lorem fistrum no puedor te va a hasé pupitaa te va a hasé pupitaa papaar papaar torpedo benemeritaar jarl condemor fistro. Te va a hasé pupitaa al ataquerl torpedo ese hombree al ataquerl la caidita tiene musho peligro qué dise usteer ese pedazo de te va a hasé pupitaa fistro. Fistro quietooor diodeno va usté muy cargadoo me cago en tus muelas va usté muy cargadoo.', image:'../../assets/images/projects/clubDisco.jpg'},
      {id: 3, author: 'Javier Vázquez', imageAuthor: '../../../assets/images/foto_linkedin_javi.png', title: 'Project C', objetive: 'App for helping dislexic people', bootcamp: 'UX/UI', description: 'Lorem fistrum no puedor te va a hasé pupitaa te va a hasé pupitaa papaar papaar torpedo benemeritaar jarl condemor fistro. Te va a hasé pupitaa al ataquerl torpedo ese hombree al ataquerl la caidita tiene musho peligro qué dise usteer ese pedazo de te va a hasé pupitaa fistro. Fistro quietooor diodeno va usté muy cargadoo me cago en tus muelas va usté muy cargadoo.', image: '../../assets/images/projects/dislexia.png' },
      {id: 1, author: 'Javier Vázquez', imageAuthor: '../../../assets/images/foto_linkedin_javi.png', title: 'Project A', objetive: 'Social Network for Neolanders', bootcamp: 'Full-Stack', description:'Lorem fistrum no puedor te va a hasé pupitaa te va a hasé pupitaa papaar papaar torpedo benemeritaar jarl condemor fistro. Te va a hasé pupitaa al ataquerl torpedo ese hombree al ataquerl la caidita tiene musho peligro qué dise usteer ese pedazo de te va a hasé pupitaa fistro. Fistro quietooor diodeno va usté muy cargadoo me cago en tus muelas va usté muy cargadoo.', image: '../../assets/images/projects/network.jpg'},
      {id: 2, author: 'Javier Vázquez', imageAuthor: '../../../assets/images/foto_linkedin_javi.png', title: 'Project B', objetive: 'A site for connecting artist and clubs', bootcamp: 'Full-Stack', description:'Lorem fistrum no puedor te va a hasé pupitaa te va a hasé pupitaa papaar papaar torpedo benemeritaar jarl condemor fistro. Te va a hasé pupitaa al ataquerl torpedo ese hombree al ataquerl la caidita tiene musho peligro qué dise usteer ese pedazo de te va a hasé pupitaa fistro. Fistro quietooor diodeno va usté muy cargadoo me cago en tus muelas va usté muy cargadoo.', image:'../../assets/images/projects/clubDisco.jpg'},
      {id: 3, author: 'Javier Vázquez', imageAuthor: '../../../assets/images/foto_linkedin_javi.png', title: 'Project C', objetive: 'App for helping dislexic people', bootcamp: 'UX/UI', description: 'Lorem fistrum no puedor te va a hasé pupitaa te va a hasé pupitaa papaar papaar torpedo benemeritaar jarl condemor fistro. Te va a hasé pupitaa al ataquerl torpedo ese hombree al ataquerl la caidita tiene musho peligro qué dise usteer ese pedazo de te va a hasé pupitaa fistro. Fistro quietooor diodeno va usté muy cargadoo me cago en tus muelas va usté muy cargadoo.', image: '../../assets/images/projects/dislexia.png' },
      {id: 1, author: 'Javier Vázquez', imageAuthor: '../../../assets/images/foto_linkedin_javi.png', title: 'Project A', objetive: 'Social Network for Neolanders', bootcamp: 'Full-Stack', description:'Lorem fistrum no puedor te va a hasé pupitaa te va a hasé pupitaa papaar papaar torpedo benemeritaar jarl condemor fistro. Te va a hasé pupitaa al ataquerl torpedo ese hombree al ataquerl la caidita tiene musho peligro qué dise usteer ese pedazo de te va a hasé pupitaa fistro. Fistro quietooor diodeno va usté muy cargadoo me cago en tus muelas va usté muy cargadoo.', image: '../../assets/images/projects/network.jpg'},
      {id: 2, author: 'Javier Vázquez', imageAuthor: '../../../assets/images/foto_linkedin_javi.png', title: 'Project B', objetive: 'A site for connecting artist and clubs', bootcamp: 'Full-Stack', description:'Lorem fistrum no puedor te va a hasé pupitaa te va a hasé pupitaa papaar papaar torpedo benemeritaar jarl condemor fistro. Te va a hasé pupitaa al ataquerl torpedo ese hombree al ataquerl la caidita tiene musho peligro qué dise usteer ese pedazo de te va a hasé pupitaa fistro. Fistro quietooor diodeno va usté muy cargadoo me cago en tus muelas va usté muy cargadoo.', image:'../../assets/images/projects/clubDisco.jpg'},
      {id: 3, author: 'Javier Vázquez', imageAuthor: '../../../assets/images/foto_linkedin_javi.png', title: 'Project C', objetive: 'App for helping dislexic people', bootcamp: 'UX/UI', description:'Lorem fistrum no puedor te va a hasé pupitaa te va a hasé pupitaa papaar papaar torpedo benemeritaar jarl condemor fistro. Te va a hasé pupitaa al ataquerl torpedo ese hombree al ataquerl la caidita tiene musho peligro qué dise usteer ese pedazo de te va a hasé pupitaa fistro. Fistro quietooor diodeno va usté muy cargadoo me cago en tus muelas va usté muy cargadoo.', image: '../../assets/images/projects/dislexia.png'}
    ]
  }

  ngOnInit() {
  }

}
